### ISSUE TITLE
这是一个简单有效的插件，希望可以迁出jdk8版本分支提供使用

### ISSUE THREAD

**Issue by obill123** [jettwangcj/redis-util-spring-boot-starter#2]
目前企业jdk8版本依旧是主流，插件似乎是基于jdk11版本并不能直接运行到我本地
开发者代码简洁明了参考价值很多，已有部分功能迁移至我jdk8版本的工程中

**Comment by jettwangcj** [comment]
本项目代码使用的是jdk8，请检查

**Comment by jettwangcj** [comment]
另外，github不再维护，如果关注该项目请访问 https://gitee.com/listen_w

**Comment by jettwangcj** [comment]
另外，github不再维护，如果关注该项目请访问 https://gitee.com/listen_w
